// packages/react-selecto/src/react-selecto/Selecto.tsx
import * as React from "react";
import VanillaSelecto, {
    CLASS_NAME,
    OPTIONS,
    SelectoOptions,
    PROPERTIES,
    SelectoProperties,
} from "selecto";
import { ref } from "framework-utils";
import { IObject } from "@daybrush/utils";

export default class Selecto extends React.PureComponent<Partial<SelectoOptions>> {
    private selecto!: VanillaSelecto;
    private selectionElement!: HTMLElement;
    public render() {
        return <div className={CLASS_NAME} ref={ref(this, "selectionElement")}></div>;
    }
    public componentDidMount() {
        const props = this.props;
        const options: Partial<SelectoOptions> = {};
        const events: IObject<any> = {};

        OPTIONS.forEach(name => {
            if (name in props) {
                (options as any)[name] = props[name];
            }
        });
        this.selecto = new VanillaSelecto({
            ...options,
            target: this.selectionElement,
        });
    }
    public componentDidUpdate(prevProps: Partial<SelectoProperties>) {
        const props = this.props;
        const selecto = this.selecto;

        PROPERTIES.forEach(name => {
            if (prevProps[name] !== props[name]) {
                (selecto as any)[name] = props[name];
            }
        });
    }
    public componentWillUnmount() {
        this.selecto.destroy();
    }
}

// packages/vue3-selecto/src/Selecto.vue
<template>
  <div ref="selectoElement"></div>
</template>
<script lang="ts">
import VanillaSelecto, {
  SelectoOptions,
  OPTIONS,
  EVENTS,
  PROPERTIES,
  METHODS,
} from "selecto";
import { isUndefined } from "@daybrush/utils";

const methods: Record<string, any> = {};

METHODS.forEach((name) => {
  methods[name] = function(this: any, ...args: any[]) {
    this.$_selecto[name](...args);
  };
});
const watch: Record<string, any> = {};

PROPERTIES.forEach((name) => {
  watch[name] = function (this: any, value: any) {
    this.$_selecto[name] = value;
  };
});
export default {
  name: "selecto",
  methods,
  props: OPTIONS,
  watch,
  mounted(this: any) {
    const props = this.$props;
    const options: Partial<SelectoOptions> = {};

    OPTIONS.forEach((name) => {
      const value = props[name];
      if (!isUndefined(value)) {
        (options as any)[name] = value;
      }
    });

    const selecto = new VanillaSelecto({
      ...options,
      target: this.$refs.target as any,
    });

    this.$_selecto = selecto;

    EVENTS.forEach((name) => {
      selecto.on(name, (e) => {
        this.$emit(name, { ...e });
      });
    });
  },
  beforeUnmount(this: any) {
    this.$_selecto.destroy();
  },
};
</script>
